name: Deploy Saleor Infrastructure

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
  TF_VAR_ssh_key_fingerprint: ${{ secrets.SSH_KEY_FINGERPRINT }}
  TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
  TF_VAR_region: ${{ secrets.DO_REGION }}
  TF_VAR_droplet_size: "s-1vcpu-2gb"
  TF_VAR_db_size: "db-s-1vcpu-1gb"
  TF_VAR_space_name: ${{ secrets.SPACE_NAME }}

jobs:
  deploy:
    name: Provision Infra & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Save droplet IP
        id: tf_output
        working-directory: terraform
        run: |
          echo "DROPLET_IP=$(terraform output -raw droplet_ip)" >> $GITHUB_ENV

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.SSH_KEY }}" | base64 -d > private_key
          chmod 600 private_key

      - name: Copy Setup Files to Droplet
        run: |
          scp -o StrictHostKeyChecking=no -i private_key -r docker/ root@${{ env.DROPLET_IP }}:/root/

      - name: Run Setup Script on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key root@${{ env.DROPLET_IP }} << EOF
            cd /root/docker
            chmod +x setup.sh
            ./setup.sh
          EOF
